--  Create table Player (
--      ID integer not null,
--      Name varchar(255) not null,
--      Nationality varchar(255) not null,
--      BirthDate timestamp,
--      Titles integer,
--      PRIMARY KEY (ID)
--  );